#include "stm32f4xx_it.h"
#include "stm32f4xx_adc.h"
#include "stm32f4xx_dac.h"
#include "stm32f4xx_gpio.h"
#include "stm32f429i_discovery.h"
#include "stdio.h"
#include "stm32f429i_discovery_lcd.h"
#include "util.h"
